---
fabric_name:     "{{ env_fabric_name | default('fabric') }}"
company_name:    "{{ env_customer_company_name | default('company') }}"
domain_name:     "{{ env_hosted_zone | default('domain') }}"
controller_fqdn: "controller-{{ fabric_name }}.{{ company_name }}.{{ domain_name }}"
orchestrator_fqdn: "orchestrator-{{ fabric_name }}.{{ company_name }}.{{ domain_name }}"

nginx_sites:     { }
nginx_streams:   { }
nginx_ssl:       { }
install_only:    False
