---
- name: "{{ ansible_distribution }} | Unattended upgrades | Adjust intervals and settings"
  template:
    src:   "templates/{{ linux_distribution }}/{{ item }}.j2"
    dest:  "/etc/apt/apt.conf.d/{{ item }}"
    force: yes
  loop:
    - "10periodic"
    - "20auto-upgrades"
    - "50unattended-upgrades"
  tags:
    - common
    - security
    - upgrades

- name: "{{ ansible_distribution }} | Unattended upgrades | Create systemd service and timer override directories"
  file:
    path:  "{{ item }}"
    owner: "root"
    group: "root"
    mode:  "0755"
    state: directory
  loop:
    - "/etc/systemd/system/apt-daily.timer.d/"
    - "/etc/systemd/system/apt-daily-upgrade.timer.d/"
  tags:
    - common
    - security
    - upgrades

- name: "{{ ansible_distribution }} | Unattended upgrades | Generate systemd timer override files"
  template:
    src:   "{{ item.src }}"
    dest:  "{{ item.dst }}"
    owner: "root"
    group: "root"
    mode:  "0644"
    force: yes
  loop:
    - { src: "templates/{{ linux_distribution }}/apt-daily-timer-d-override.conf.j2",         dst: "/etc/systemd/system/apt-daily.timer.d/override.conf"         }
    - { src: "templates/{{ linux_distribution }}/apt-daily-upgrade-timer-d-override.conf.j2", dst: "/etc/systemd/system/apt-daily-upgrade.timer.d/override.conf" }
  notify:
    - "{{ linux_distribution }} restart apt-daily.timer"
    - "{{ linux_distribution }} restart apt-daily-upgrade.timer"
  tags:
    - common
    - security
    - upgrades
