---
fabric_name: "{{ env_fabric_name | default('fabric') }}"
company_name: "{{ env_customer_company_name | default('company') }}"
domain_name: "{{ env_hosted_zone | default('domain') }}"
node_type: "{{ node_type | default('node')"
x509_root_dir: "/opt/bayware"
x509_user: "{{ ansible_user }}"
x509_sub_o: "{{ company_name }}"
x509_sub_ou: "{{ fabric_name }}"
x509_ca_host: "localhost"
x509_ca_root_dir: "~/.bwctl"
x509_ca_crt_dir: "{{ x509_ca_root_dir }}/{{ fabric_name }}"
x509_ca_crt_file: "rootca.crt"
x509_ca_key_file: "rootca.key"
x509_crt_dir: "{{ x509_root_dir }}/certs"
x509_crt_ca_file: "ca.crt"
x509_crt_list:
  - { name: "node",
      ext_file: "node_crt_extensions.ext",
      subj: "/O={{ x509_sub_o }}/DC={{ x509_sub_ou }}/DC={{ node_type }}/CN={{ inventory_hostname }}",
      key_type: "rsa"
  }
