---
- name: Letsencrypt | Add certbot renewal cron job
  cron:
    name:   "Letsencrypt certbot automatic renewal"
    job:    "{{ certbot_script }} renew {{ certbot_auto_renew_options }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour:   "{{ certbot_auto_renew_hour }}"
    user:   "{{ certbot_auto_renew_user }}"
