---
# 23-Oct-2019, @vovin
# As Ansible pre-processes all static imports (import_*) during Playbook parsing time, it's not possible to use variables in task names,
# so dynamic includes to be used (include_*). To have it done in the same manner, all includes would be dynamic.
# For more information, refer to:
#   - https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse.html#tradeoffs-and-pitfalls-between-includes-and-imports
#
# Common tasks
- include_tasks: "base-common.yml"
- include_tasks: "base-{{ linux_distribution }}.yml"

# Python
- include_tasks: "python-common.yml"
- include_tasks: "python-{{ linux_distribution }}.yml"

# rsyslog
- include_tasks: "rsyslog-common.yml"

# ssh
- include_tasks: "ssh-common.yml"
