---
fabric_name:       "{{ env_fabric_name | default('fabric') }}"
company_name:      "{{ env_customer_company_name | default('company') }}"
domain_name:       "{{ env_hosted_zone | default('domain') }}"
controller_passwd: "{{ env_controller_passwd | default(omit) }}"
controller_fqdn:   "orchestrator-{{ fabric_name }}.{{ company_name }}.{{ domain_name }}"

manager_host:      "{{ env_swarm_manager_host | default(inventory_hostname) }}"

bw_home_dir:       "/opt/bayware"
update_controller: False
