---
- name: terraform | install dependencies
  apt:
    name: "unzip"
  tags:
    - terraform
  register: terraform_apt_dependencies_result
  retries:  "{{ ansible_task_retries }}"
  until:    terraform_apt_dependencies_result is succeeded

- name: terraform | check version
  shell: "set -o pipefail && terraform --version | head -n1 | grep {{ terraform_version }}"
  args:
    executable: /bin/bash
  failed_when: False
  changed_when: False
  register: current_terraform_version
  tags:
    - terraform

- name: terraform | get checksums
  uri:
    url:    "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_SHA256SUMS"
    method: "GET"
    return_content: yes
  register: terraform_checksums
  tags:
    - terraform

- name: terraform | download
  get_url:
    url:      "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest:     "/usr/local/src/terraform_{{ terraform_version }}_linux_amd64.zip"
    checksum: "sha256:{{ item.split(' ') | first }}"
  with_items: "{{ terraform_checksums.content.split('\n') | select('search', 'linux_amd64') | list | first }}"
  register: terraform_downloaded
  tags:
    - terraform

- name: terraform | install
  unarchive:
    src:  "/usr/local/src/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/usr/local/bin"
    copy: no
  when: current_terraform_version.rc != 0 or terraform_downloaded is changed
  tags:
    - terraform
